---
name: "Jfresolve"
guid: "506F18B8-5DAD-4CD3-B9A0-F7ED933E9939"
version: "11.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Integrates remote streaming (Real-Debrid, TMDb, etc.) into Jellyfin."
description: >
  This is Jfresolve.
category: "General"
owner: "vicking20"
imageUrl: "https://raw.githubusercontent.com/vicking20/jfresolve/main/jfresolve.png"
artifacts:
  - "Jfresolve.dll"
changelog: >
  changelog
